apiVersion: v1
kind: Pod
metadata:
  name: book-review-pod
  labels:
    app: book-review
spec:
 containers:
  - name: book-review
    image: book-review
    imagePullPolicy: Never
    ports:
      - containerPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: book-review-service
spec:
  selector:
    app: book-review
  ports:
    - port: 8090
      targetPort: 8090
      nodePort: 30001
  type: NodePort
