apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: book
  template:
    metadata:
      labels:
        app: book
    spec:
      containers:
        - name: book
          image: book-servicer:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8092
---
apiVersion: v1
kind: Service
metadata:
  name: book-service
spec:
  selector:
    app: book
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: ClusterIP
